language: r

r_binary_packages:
    - BBmisc
    - checkmate
    - brew
    - digest
    - fail
    - DBI
    - RSQLite
    - stringi
    - testthat

r_github_packages:
    - jimhester/covr

after_success:
    - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
